import type {
  Trip,
  ItineraryStop,
  Activity,
  Budget,
  DestinationCard,
} from "@/types";

// ─── Mock Destinations ────────────────────────────────────────────────────────

export const mockDestinations: DestinationCard[] = [
  {
    id: "d1",
    name: "Tokyo",
    country: "Japan",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&auto=format&fit=crop&q=60",
    tag: "Cultural",
    tripCount: 3420,
  },
  {
    id: "d2",
    name: "Bali",
    country: "Indonesia",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=60",
    tag: "Relaxation",
    tripCount: 2891,
  },
  {
    id: "d3",
    name: "Paris",
    country: "France",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&auto=format&fit=crop&q=60",
    tag: "Romantic",
    tripCount: 4120,
  },
  {
    id: "d4",
    name: "New York",
    country: "USA",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&auto=format&fit=crop&q=60",
    tag: "Urban",
    tripCount: 5003,
  },
  {
    id: "d5",
    name: "Santorini",
    country: "Greece",
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&auto=format&fit=crop&q=60",
    tag: "Scenic",
    tripCount: 1987,
  },
  {
    id: "d6",
    name: "Machu Picchu",
    country: "Peru",
    image: "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&auto=format&fit=crop&q=60",
    tag: "Adventure",
    tripCount: 1544,
  },
];

// ─── Mock Activities ──────────────────────────────────────────────────────────

const tokyoDay1Activities: Activity[] = [
  {
    id: "act1",
    trip_id: "trip1",
    stop_id: "stop1",
    name: "Arrive at Narita International Airport",
    description: "Collect luggage, clear customs, take Narita Express to Shinjuku.",
    category: "transport",
    cost: 30,
    duration_hr: 2,
    start_time: "14:00",
    day_number: 1,
    order_index: 0,
    score: null,
    created_at: "2025-03-20T00:00:00Z",
  },
  {
    id: "act2",
    trip_id: "trip1",
    stop_id: "stop1",
    name: "Check-in at Shinjuku Granbell Hotel",
    description: "Modern boutique hotel in the heart of Shinjuku.",
    category: "accommodation",
    cost: 180,
    duration_hr: 0.5,
    start_time: "17:00",
    day_number: 1,
    order_index: 1,
    score: null,
    created_at: "2025-03-20T00:00:00Z",
  },
  {
    id: "act3",
    trip_id: "trip1",
    stop_id: "stop1",
    name: "Explore Shinjuku at Night",
    description: "Wander Kabukicho entertainment district, neon lights, ramen.",
    category: "attraction",
    cost: 25,
    duration_hr: 3,
    start_time: "19:00",
    day_number: 1,
    order_index: 2,
    score: null,
    created_at: "2025-03-20T00:00:00Z",
  },
];

const tokyoDay2Activities: Activity[] = [
  {
    id: "act4",
    trip_id: "trip1",
    stop_id: "stop1",
    name: "Breakfast at Tsukiji Outer Market",
    description: "Fresh seafood, tamagoyaki, matcha. Arrive early for the best picks.",
    category: "food",
    cost: 20,
    duration_hr: 1.5,
    start_time: "08:00",
    day_number: 2,
    order_index: 0,
    score: null,
    created_at: "2025-03-21T00:00:00Z",
  },
  {
    id: "act5",
    trip_id: "trip1",
    stop_id: "stop1",
    name: "Senso-ji Temple, Asakusa",
    description: "Tokyo's most famous Buddhist temple. Visit Thunder Gate, browse Nakamise Street.",
    category: "attraction",
    cost: 0,
    duration_hr: 2,
    start_time: "10:00",
    day_number: 2,
    order_index: 1,
    score: null,
    created_at: "2025-03-21T00:00:00Z",
  },
  {
    id: "act6",
    trip_id: "trip1",
    stop_id: "stop1",
    name: "Lunch in Harajuku",
    description: "Crepes on Takeshita Street, unique fashion district exploration.",
    category: "food",
    cost: 15,
    duration_hr: 1.5,
    start_time: "13:00",
    day_number: 2,
    order_index: 2,
    score: null,
    created_at: "2025-03-21T00:00:00Z",
  },
  {
    id: "act7",
    trip_id: "trip1",
    stop_id: "stop1",
    name: "Shibuya Crossing & Sky Bar",
    description: "World's busiest pedestrian crossing at dusk, drinks at a sky bar.",
    category: "attraction",
    cost: 40,
    duration_hr: 3,
    start_time: "17:00",
    day_number: 2,
    order_index: 3,
    score: null,
    created_at: "2025-03-21T00:00:00Z",
  },
];

const kyotoDay3Activities: Activity[] = [
  {
    id: "act8",
    trip_id: "trip1",
    stop_id: "stop2",
    name: "Shinkansen to Kyoto",
    description: "2h15m bullet train from Shinagawa to Kyoto station.",
    category: "transport",
    cost: 70,
    duration_hr: 2.5,
    start_time: "08:30",
    day_number: 3,
    order_index: 0,
    score: null,
    created_at: "2025-03-22T00:00:00Z",
  },
  {
    id: "act9",
    trip_id: "trip1",
    stop_id: "stop2",
    name: "Fushimi Inari-taisha",
    description: "Thousands of vermilion torii gates winding through forested hills.",
    category: "attraction",
    cost: 0,
    duration_hr: 3,
    start_time: "11:00",
    day_number: 3,
    order_index: 1,
    score: null,
    created_at: "2025-03-22T00:00:00Z",
  },
  {
    id: "act10",
    trip_id: "trip1",
    stop_id: "stop2",
    name: "Kaiseki Dinner",
    description: "Traditional multi-course Japanese cuisine in Gion district.",
    category: "food",
    cost: 85,
    duration_hr: 2,
    start_time: "19:00",
    day_number: 3,
    order_index: 2,
    score: null,
    created_at: "2025-03-22T00:00:00Z",
  },
];

// ─── Mock Itinerary Stops ─────────────────────────────────────────────────────

const japanStops: ItineraryStop[] = [
  {
    id: "stop1",
    trip_id: "trip1",
    city: "Tokyo",
    country: "Japan",
    day_number: 1,
    order_index: 0,
    arrival: "2025-03-20",
    departure: "2025-03-22",
    stay_cost: 360,
    notes: "Stay at Shinjuku Granbell. JR Pass valid here.",
    created_at: "2025-01-10T00:00:00Z",
    activities: [...tokyoDay1Activities, ...tokyoDay2Activities],
  },
  {
    id: "stop2",
    trip_id: "trip1",
    city: "Kyoto",
    country: "Japan",
    day_number: 3,
    order_index: 1,
    arrival: "2025-03-22",
    departure: "2025-03-25",
    stay_cost: 420,
    notes: "Ryokan experience recommended. Nishiki Market nearby.",
    created_at: "2025-01-10T00:00:00Z",
    activities: kyotoDay3Activities,
  },
  {
    id: "stop3",
    trip_id: "trip1",
    city: "Osaka",
    country: "Japan",
    day_number: 6,
    order_index: 2,
    arrival: "2025-03-25",
    departure: "2025-03-27",
    stay_cost: 280,
    notes: "Dotonbori street food is unmissable. Visit Osaka Castle.",
    created_at: "2025-01-10T00:00:00Z",
    activities: [],
  },
];

// ─── Mock Budgets ─────────────────────────────────────────────────────────────

const japanBudget: Budget = {
  id: "budget1",
  trip_id: "trip1",
  total_budget: 3200,
  transport_est: 520,
  accommodation_est: 1060,
  food_est: 560,
  activities_est: 380,
  misc_est: 280,
  currency: "USD",
  updated_at: "2025-01-10T00:00:00Z",
  daily_average: 457,
  alert: null,
};

const baliTrip2Budget: Budget = {
  id: "budget2",
  trip_id: "trip2",
  total_budget: 1800,
  transport_est: 350,
  accommodation_est: 600,
  food_est: 350,
  activities_est: 280,
  misc_est: 220,
  currency: "USD",
  updated_at: "2025-01-10T00:00:00Z",
  daily_average: 257,
  alert: null,
};

// ─── Mock Trips ───────────────────────────────────────────────────────────────

export const mockTrips: Trip[] = [
  {
    id: "trip1",
    user_id: "user1",
    title: "Japan Spring Adventure",
    description: "Cherry blossoms, ancient temples, street food, and bullet trains through Japan's most iconic cities.",
    cover_image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&auto=format&fit=crop&q=60",
    start_date: "2025-03-20",
    end_date: "2025-03-27",
    status: "upcoming",
    is_public: true,
    remixed_from_id: null,
    remix_count: 42,
    trip_score: 87,
    created_at: "2025-01-10T00:00:00Z",
    updated_at: "2025-01-10T00:00:00Z",
    stops: japanStops,
    budget: japanBudget,
    duration_days: 7,
    _count: { activities: 10, stops: 3 },
  },
  {
    id: "trip2",
    user_id: "user1",
    title: "Bali Wellness Retreat",
    description: "A mindful journey through Bali's rice terraces, sacred temples, and yoga retreats.",
    cover_image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=60",
    start_date: "2025-06-10",
    end_date: "2025-06-17",
    status: "upcoming",
    is_public: false,
    remixed_from_id: null,
    remix_count: 0,
    trip_score: 72,
    created_at: "2025-02-15T00:00:00Z",
    updated_at: "2025-02-20T00:00:00Z",
    stops: [
      {
        id: "stop4",
        trip_id: "trip2",
        city: "Ubud",
        country: "Indonesia",
        day_number: 1,
        order_index: 0,
        arrival: "2025-06-10",
        departure: "2025-06-14",
        stay_cost: 320,
        notes: "Book yoga retreat in advance.",
        created_at: "2025-02-15T00:00:00Z",
        activities: [],
      },
      {
        id: "stop5",
        trip_id: "trip2",
        city: "Seminyak",
        country: "Indonesia",
        day_number: 5,
        order_index: 1,
        arrival: "2025-06-14",
        departure: "2025-06-17",
        stay_cost: 280,
        notes: "Beach clubs and sunset dinners.",
        created_at: "2025-02-15T00:00:00Z",
        activities: [],
      },
    ],
    budget: baliTrip2Budget,
    duration_days: 7,
    _count: { activities: 5, stops: 2 },
  },
  {
    id: "trip3",
    user_id: "user1",
    title: "Paris Weekend Getaway",
    description: "A romantic weekend exploring Parisian cafés, art museums, and the Eiffel Tower.",
    cover_image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&auto=format&fit=crop&q=60",
    start_date: "2024-11-01",
    end_date: "2024-11-03",
    status: "completed",
    is_public: true,
    remixed_from_id: null,
    remix_count: 18,
    trip_score: 91,
    created_at: "2024-10-01T00:00:00Z",
    updated_at: "2024-11-05T00:00:00Z",
    stops: [],
    budget: null,
    duration_days: 2,
    _count: { activities: 8, stops: 1 },
  },
  {
    id: "trip4",
    user_id: "user1",
    title: "NYC Food Tour",
    description: "Eating through New York — from Brooklyn pizza to Michelin-starred dining.",
    cover_image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&auto=format&fit=crop&q=60",
    start_date: "2025-01-05",
    end_date: "2025-01-08",
    status: "draft",
    is_public: false,
    remixed_from_id: null,
    remix_count: 0,
    trip_score: 45,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-02T00:00:00Z",
    stops: [],
    budget: null,
    duration_days: 3,
    _count: { activities: 2, stops: 0 },
  },
];

// ─── Public Trips (Explore feed) ──────────────────────────────────────────────

export const mockPublicTrips: Trip[] = [
  {
    ...mockTrips[0],
    id: "pub1",
    user: { id: "u2", name: "Sarah Miller", avatar_url: null },
    title: "14 Days of Cherry Blossoms",
    description: "My personal route to catch the sakura season at its peak. Starts in Tokyo, ends in Kyoto.",
  },
  {
    ...mockTrips[2],
    id: "pub2",
    user: { id: "u3", name: "James K.", avatar_url: null },
    title: "Hidden Paris (No Tourists)",
    description: "Forget the Louvre. These are the hidden cafés and secret gardens locals actually go to.",
  },
  {
    id: "pub3",
    user_id: "u4",
    title: "Southeast Asia Backpacker Loop",
    description: "Vietnam → Cambodia → Thailand on a budget. 3 weeks, 3 countries.",
    cover_image: "https://images.unsplash.com/photo-1528127269322-539801943592?w=800&auto=format&fit=crop&q=80",
    start_date: "2025-02-01",
    end_date: "2025-02-21",
    status: "completed",
    is_public: true,
    remixed_from_id: null,
    remix_count: 93,
    trip_score: 95,
    created_at: "2024-12-01T00:00:00Z",
    updated_at: "2025-02-22T00:00:00Z",
    stops: [],
    budget: null,
    duration_days: 21,
    _count: { activities: 28, stops: 6 },
    user: { id: "u4", name: "Priya Lakshmi", avatar_url: null },
  },
  {
    id: "pub4",
    user_id: "u5",
    title: "Iceland Ring Road Adventure",
    description: "Glaciers, waterfalls, and the northern lights. A 10-day road trip around the edge of the world.",
    cover_image: "https://images.unsplash.com/photo-1476610182048-b716b8518aae?w=800&auto=format&fit=crop&q=80",
    start_date: "2025-09-10",
    end_date: "2025-09-20",
    status: "completed",
    is_public: true,
    remixed_from_id: null,
    remix_count: 214,
    trip_score: 98,
    created_at: "2024-11-01T00:00:00Z",
    updated_at: "2025-01-22T00:00:00Z",
    stops: [],
    budget: null,
    duration_days: 10,
    _count: { activities: 14, stops: 5 },
    user: { id: "u5", name: "Marcus Chen", avatar_url: null },
  },
];

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export interface DashboardStats {
  totalTrips: number;
  upcomingTrips: number;
  citiesVisited: number;
  avgTripScore: number;
}

export function getMockDashboardStats(): DashboardStats {
  return {
    totalTrips: mockTrips.length,
    upcomingTrips: mockTrips.filter((t) => t.status === "upcoming").length,
    citiesVisited: 12,
    avgTripScore: 74,
  };
}

export function getMockTripById(id: string): Trip | undefined {
  return [...mockTrips, ...mockPublicTrips].find((t) => t.id === id);
}

export function getMockTripsByStatus(status: Trip["status"]): Trip[] {
  return mockTrips.filter((t) => t.status === status);
}
